
default: &default
 adapter: postgresql
 encoding: unicode
 database: hrm_development
 username: rails
 password: password
 pool: 5
 host: localhost

development:
 <<: *default
 database: hrm_development

test:
 <<: *default
 database: hrm_test

production:
 <<: *default
 database: hrm_production
 username: rails
 password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>