default: &default
 adapter: postgresql
 encoding: unicode
 database: rails_database
 username: rails_app
 password: password
 pool: 5
 host: localhost

development:
 <<: *default
 database: rails_database

test:
 <<: *default
 database: rails_database

production:
 <<: *default
 database: rails_database
 username: rails_app
 password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>